### ISSUE TITLE
Mixmaster remailers

### ISSUE THREAD

**Issue by inwtx** [katzenpost/website#10]
We who are running mixmaster remailers are very interested in this project.  Once it is packaged, many remailer sysops will most likely run a mixnet system on their servers.  Keep up the good work!

**Comment by david415** [comment]
ok. please do let us know if these instructions work for you 
https://katzenpost.mixnetworks.org/docs/setup.html

you can then use the daemons/mailproxy client to test it...
hmm probably we need to add more documentation for this.

**Comment by moba** [comment]
Thanks @inwtx, this comment is appreciated. Still, let me do some housekeeping and close this ticket. :)

There's lots of areas where we can use help, many of which do not require any special knowledge. Check out https://github.com/katzenpost/mixnet_uprising/issues and get in touch on IRC (oftc #katzenpost).
