### ISSUE TITLE
katzenpost/website/docs and katzenpost/docs

### ISSUE THREAD

**Issue by juga0** [katzenpost/website#9]
Since [katzenpost/docs](https://github.com/katzenpost/docs) contains also the the specs and drafts, it might be useful to either:

1. remove that repository if the specs and drafts are going to live in this repo
2. keep both repositories separated and link the documentation using [intersphinx](http://www.sphinx-doc.org/en/stable/tutorial.html#intersphinx)
3. keep both repos and add here  [katzenpost/docs](https://github.com/katzenpost/docs) as a git submodule/subproject/etc.
4. other ideas...

**Comment by moba** [comment]
The idea is that once the restructuredText versions produce nice **plaintext** output, we ditch the current plaintext copies and the docs repo altogether. For example, I really don't like how the TOC is presented in the default sphinx TextBuilder output. David does not want to give up the RFC-style plaintext versions, and I tend to agree.
